name: "Regenerate all Podcasts JSON files"
on:
  schedule:
    - cron: "0 1 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  regenerate_all_json:
    runs-on: ubuntu-latest
    steps:
      - name: regenerate all Podcasts JSON files
        uses: pcarion/awesome-podcasts-bot@v0.21
        with:
          repo-token: ${{ secrets.GH_PAT }}


