name: Deploy podcastfr.com
on:
  repository_dispatch:
    types: [deploy]
  push:
    branches: main
    paths:
    - content/podcasts.json
jobs:
  build:
    name: deploying podcastfr.com
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: set github identity
        run: |
          git config --global user.email "pcarion@gmail.com"
          git config --global user.name "Pierre Carion"
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" > ~/.npmrc
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}
      - run: env
      - run: npm run buildcss
      - run: npm run generate
      - run: ls -lR __html__
